import { useMemo } from 'react'
import { fsUpdateTransaction } from '../lib/firestore'
import { confirmApp, notifyApp } from '../lib/appFeedback'
import { RECUR_OPTIONS, fmt, playTick, formatDisplayDate, displayValue, maskMoney } from '../lib/utils'
import styles from './Page.module.css'
import sStyles from './Subscriptions.module.css'
import { getRecurringOccurrenceKey } from '../lib/recurrence'

export default function Subscriptions({ user, data, symbol, privacyMode = false }) {
  const s = symbol || '₱'
  const money = value => displayValue(privacyMode, fmt(value, s), maskMoney(s))

  const activeSubscriptions = useMemo(() => {
    const allTx = [...(data?.income || []), ...(data?.expenses || [])]
    const chains = {}
    
    allTx.forEach(tx => {
      const chainId = tx.recurrenceSourceId || tx._id
      if (!chains[chainId]) chains[chainId] = []
      chains[chainId].push(tx)
    })
    
    const active = []
    Object.values(chains).forEach(chain => {
      // Sort by actual date descending to find the latest
      chain.sort((a, b) => (b.date || '').localeCompare(a.date || ''))
      const latest = chain[0]
      // Only include if it has an active recur rule
      if (latest.recur) {
        active.push(latest)
      }
    })
    
    active.sort((a, b) => {
      const aType = a.type === 'income' ? 1 : 0
      const bType = b.type === 'income' ? 1 : 0
      if (aType !== bType) return bType - aType
      return b.amount - a.amount
    })
    return active
  }, [data?.income, data?.expenses])

  async function handleStopRecurrence(tx) {
    playTick()
    const confirmed = await confirmApp({
      title: 'Stop Subscriptions?',
      message: `Stop the recurring rule for ${tx.desc || tx.cat}? This won't delete past records, but the auto-engine will stop generating future cycles.`,
      confirmLabel: 'Stop recurring',
      cancelLabel: 'Keep active',
      tone: 'danger',
    })
    if (!confirmed) return

    try {
      const col = tx.type === 'income' ? 'income' : 'expenses'
      await fsUpdateTransaction(user.uid, col, tx, { recur: '' }, data.accounts)
      notifyApp({
        title: 'Subscription stopped',
        message: `${tx.desc || tx.cat} will no longer recur.`,
        tone: 'success'
      })
    } catch (err) {
      console.error(err)
      notifyApp({
        title: 'Error',
        message: 'Could not update recurrence right now.',
        tone: 'error'
      })
    }
  }

  const renderSubCard = (tx) => {
    const freqLabel = RECUR_OPTIONS.find(o => o.value === tx.recur)?.label || tx.recur
    const isIncome = tx.type === 'income'
    const occurrenceDate = getRecurringOccurrenceKey(tx) || tx.date
    
    return (
      <div key={tx._id} className={sStyles.subCard}>
        <div className={sStyles.subCardHeader}>
          <div>
            <h4 className={sStyles.subCardTitle}>{tx.desc || tx.cat}</h4>
            <span className={sStyles.subCardSubcat}>{tx.subcat || tx.cat}</span>
          </div>
          <span className={isIncome ? sStyles.badgeIncome : sStyles.badgeExpense}>
            {isIncome ? 'Income' : 'Expense'}
          </span>
        </div>
        
        <div className={sStyles.subCardBody}>
          <div className={sStyles.subCardDetail}>
            <span className={bStyles?.detailLabel || sStyles.detailLabel}>Amount</span>
            <strong className={isIncome ? sStyles.amountIncome : sStyles.amountExpense}>
              {isIncome ? '+' : '-'}{money(tx.amount)}
            </strong>
          </div>
          <div className={sStyles.subCardDetail}>
            <span className={sStyles.detailLabel}>Frequency</span>
            <span className={sStyles.detailValue}>{freqLabel}</span>
          </div>
          <div className={sStyles.subCardDetail}>
            <span className={sStyles.detailLabel}>Last recorded</span>
            <span className={sStyles.detailValue}>{formatDisplayDate(occurrenceDate)}</span>
          </div>
        </div>
        
        <div className={sStyles.subCardFooter}>
          <button type="button" className={sStyles.stopBtn} onClick={() => handleStopRecurrence(tx)}>
            Stop recurring
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className={styles.page}>
      <div className={styles.header}>
        <div className={styles.title}>Subscriptions</div>
        <div className={styles.sub}>
          View and manage active recurring income and expenses generated by the auto-engine.
        </div>
      </div>

      <div className={sStyles.subGrid}>
        {activeSubscriptions.length > 0 ? (
          activeSubscriptions.map(renderSubCard)
        ) : (
          <div className={sStyles.emptyState}>
            <h4>No active subscriptions</h4>
            <p>Any transaction with a repeating frequency will appear here.</p>
          </div>
        )}
      </div>
    </div>
  )
}
